services:
  - type: web
    name: hotel-booking-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    nodeVersion: 22.14.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
