services:
  - type: web
    name: hotel-booking-mern
    env: node
    nodeVersion: 18.19.0
    buildCommand: |
      # Build backend
      cd backend
      npm install
      npm run build
      # Build frontend
      cd ../frontend
      npm install
      npm run build
      # Copy frontend build to backend dist
      cp -r dist ../backend/dist/frontend
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://hotel-booking-mern.onrender.com
