services:
  - type: web
    name: hotel-booking-api
    env: node
    nodeVersion: 18.19.0
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
